name: sarthi_flutter
version: 1.0.0+1
description: Futuristic AI-powered driving assistant
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  animated_background: ^2.0.0
  rive: ^0.12.4
  flutter_blue_plus: ^1.16.5
  http: ^1.2.1
  mqtt_client: ^10.2.0
  web_socket_channel: ^2.4.0
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  provider: ^6.1.2
  fl_chart: ^0.66.0
  awesome_notifications: ^0.10.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  flutter_neumorphic: ^3.2.0
  flutter_animate: ^4.2.0
  animated_toggle_switch: ^0.6.0
  lottie: ^3.1.0
  get_it: ^7.6.7
  json_annotation: ^4.9.0
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/
    - assets/lottie/
